version: "3"
services:
  web:
    container_name: web_server
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mysql
    external_links:
     - mysql
    
  mysql:
    container_name: mysqlContainer
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123
      - MYSQL_DATABASE=mysqltest
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Mysql@123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
      